Repository mash-up-kr/branding-backend, pull requests merged in 2020-08, with the labels that each got.

#40 [MODIFY] URL Main Path 변경
  src/app.js
  src/app/index.js
Labels: 수정

#38 [ADD] Authorization Header의 Value(JWT 타입 추가- Bearer) 변경
  src/app/user/service/auth_service.js
  src/common/auth/auth.js
  src/common/auth/jwt.js
Labels: 기능 개발, 수정

#66 Feature/cleanup
  package-lock.json
  package.json
  src/app.js
  src/app/applicant/api/controller/applicant_controller.js
  src/app/applicant/api/controller/applicant_status_controller.js
  src/app/applicant/api/router/applicant_router.js
  src/app/applicant/api/router/applicant_status_router.js
  src/app/applicant/domain/answer.js
  src/app/applicant/domain/applicant.js
  src/app/applicant/domain/application_status.js
  src/app/applicant/domain/question.js
  src/app/applicant/infrastructure/applicant_status_repository.js
  src/app/applicant/infrastructure/google_sheet.js
  src/app/applicant/infrastructure/google_sheet_repository.js
  src/app/applicant/infrastructure/resume_repository.js
  src/app/applicant/service/answer_service.js
  src/app/applicant/service/applicant_service.js
  src/app/applicant/service/applicant_status_service.js
  src/app/applicant/service/question_service.js
  src/app/applicant/service/resume_from_service.js
  src/app/applicant/service/resume_service.js
  src/app/index.js
  src/app/recruitment/domain/qna.js
  src/app/recruitment/domain/recruiting.js
  src/app/team/domain/team.js
  src/app/team/service/team_service.js
  src/app/user/api/controller/auth_controller.js
  src/app/user/domain/user.js
  src/common/auth/auth.js
  src/common/auth/jwt.js
  src/common/model/sequelize.js
Labels: 리팩토링

#63 모집 공고 Read, Update 구현
  src/app/index.js
  src/app/recruitment/api/controller/.keep
  src/app/recruitment/api/controller/recruitment_controller.js
  src/app/recruitment/api/router/recruitment_router.js
  src/app/recruitment/domain/recruiting.js
  src/app/recruitment/service/.keep
  src/app/recruitment/service/recruitment_service.js
  src/util/time_coverter.js
Labels: 기능 개발

#64 공통 질문(FAQ) Create, Delete, List Read 구현
  src/app/recruitment/api/controller/faq_controller.js
  src/app/recruitment/api/router/recruitment_router.js
  src/app/recruitment/domain/faq.js
  src/app/recruitment/service/faq_service.js
  src/app/recruitment/service/recruitment_service.js
  src/common/model/sequelize.js
Labels: 기능 개발

#65 모집 팀정보 Create, List Read, Read, Update, Delete 구현
  src/app/applicant/service/applicant_service.js
  src/app/applicant/service/resume_service.js
  src/app/index.js
  src/app/recruitment/api/controller/team_controller.js
  src/app/recruitment/api/router/recruitment_router.js
  src/app/recruitment/domain/team.js
  src/app/recruitment/service/team_service.js
  src/app/team/api/controller/.keep
  src/app/team/service/team_service.js
  src/common/model/sequelize.js
Labels: 기능 개발
